### ISSUE TITLE
Add SD card button on the quick access menu

### ISSUE THREAD

**Issue by joe32** [TFyre/bambu-farm#10]
add a sd card button here
![image](https://github.com/TFyre/bambu-farm/assets/78875887/1c55c91b-46e4-4bbc-b9c2-592e9a7a785f)

**Comment by TFyre** [comment]
2nd button is sd card;)

Op za 27 jan. 2024 01:05 schreef joe32 ***@***.***>:

**Comment by TFyre** [comment]
The 2nd button is SD card
