### ISSUE TITLE
What are these IP and port?

### ISSUE THREAD

**Issue by tommy4111** [TFyre/bambu-farm#111]
Trying to get the camera to work, but I don't know where to get these numbers:

PRINTER_PORT  (8883? 322?)
webrtcAdditionalHosts (docker host? where is that?)

**Comment by TFyre** [comment]
The ports are standard and should not be fiddled with unless you are doing some portforwarding or something very specific
* TCP 8883 = MQTT for Bambu Commands
* TCP 322 = RTSP Video Stream for X1C

webrtcAdditionalHosts  this should be the public facing IP address of the device where docker is running (doesnt have to be public ip, but the IP thats facing to the LAN/home network)
