### ISSUE TITLE
X1C with more than 1 AMS not showing filament running

### ISSUE THREAD

**Issue by blasirio** [TFyre/bambu-farm#26]
In the pic, it was running black filament.

![image](https://github.com/TFyre/bambu-farm/assets/126421140/f85bb6b7-286f-47a1-ad51-e5217ad9ed11)

![image](https://github.com/TFyre/bambu-farm/assets/126421140/5e7f221b-436d-4ba9-bb9b-cee9d4fd3957)

**Comment by TFyre** [comment]
1) looks like your video is not working, have you checked out the details on the docker solution for video on X1C: https://github.com/TFyre/bambu-farm/tree/main/docker/bambu-liveview

2) can you please go to "Show  Logs" for this printer, in the filter box put "tray_now", select the first message and share the text from the "RAW" box. You can replace any identifiable information like serial numbers / ip addresses etc with "REDACTED"

**Comment by TFyre** [comment]
Please try version 1.0.8 and let me know 😄
