### ISSUE TITLE
Running on docker

### ISSUE THREAD

**Issue by skydoy** [TFyre/bambu-farm#29]
I would like to get this working on docker and i would like to help if possible

**Comment by TFyre** [comment]
Its already running in docker... check out   https://github.com/TFyre/bambu-farm/blob/main/docker/bambu-liveview/example%20-%20compose.yml#L19-L27

**Comment by TFyre** [comment]
Did you manage to get this sorted? Is there something I should add to the documentation?

**Comment by skydoy** [comment]
container running and nor just need to config .env file
