### ISSUE TITLE
Printer notifications obscure the interface

### ISSUE THREAD

**Issue by wieckowy** [TFyre/bambu-farm#3]
Notifications sent by the printer cover the entire interface.
![2024-01-23_230035](https://github.com/TFyre/bambu-farm/assets/1842207/4dae5e07-7c89-4d28-b598-5c579f516d43)

**Comment by TFyre** [comment]
If you click on them, they go away :)

Is that ok?

**Comment by wieckowy** [comment]
Yes, of course :) But these notifications could be much smaller and appear in the corner of the screen.

**Comment by TFyre** [comment]
This will go out with the next update, let me know if its better/worse :)

![image](https://github.com/TFyre/bambu-farm/assets/1469570/94e4f1bd-c3d0-4612-936d-5e758aeffba9)

**Comment by wieckowy** [comment]
Amazing, thanks!
![2024-01-24_220705](https://github.com/TFyre/bambu-farm/assets/1842207/59e654b5-6ea6-4794-806b-3a8d98dfc044)

PS - I confirm that uploading files and printing works in Bambu A1.
