### ISSUE TITLE
Clear old info after printing is finished

### ISSUE THREAD

**Issue by fluppir** [TFyre/bambu-farm#37]
When the print is done, the details about the print still shows even after refreshing. If the print is done, I think it should clear the info.

Same with, when stopping a print, the details about the previous print is showing still.

**Comment by TFyre** [comment]
As discussed, when printer becomes idle, clear the frontend elements for filename / time remaining / layer count and set the progressbar to 0

Additionally, below the image, align the time to the left and add the status (eg Status: Idle) to the right. When in errorstate, change font color to red
