### ISSUE TITLE
Having ams colour selectionw would be great

### ISSUE THREAD

**Issue by joe32** [TFyre/bambu-farm#6]
being able to choose which slots to use for each colour
![Screenshot 2024-01-24 at 5 57 38 pm](https://github.com/TFyre/bambu-farm/assets/78875887/ddd0ac79-7299-4ca8-8462-e821da121930)
![Screenshot 2024-01-24 at 5 57 35 pm](https://github.com/TFyre/bambu-farm/assets/78875887/40c8b1ef-fc72-4725-9227-c1921012d795)
![Screenshot 2024-01-24 at 5 57 31 pm](https://github.com/TFyre/bambu-farm/assets/78875887/3299f585-7b6e-4214-8c35-95fb8ccdca48)

**Comment by TFyre** [comment]
https://github.com/TFyre/bambu-farm/releases/tag/v1.0.8

Version 1.0.8 has Batch Printing which allows you to select the filament mapping 😄
