### ISSUE TITLE
Feature request: Update to use device MAC address instead of Static IP configuration or choice between the two

### ISSUE THREAD

**Issue by dMAC95** [TFyre/bambu-farm#61]
Would be helpful to use a MAC address lookup to determine IP address in cases where the IP isn't static.

**Comment by TFyre** [comment]
I dont think mac2ip is the right approach. This is an IP based system, so you can use a static ip on the printer, a dynamic ip via dhcp or even a dns address. Any of those are much more stable and reliable than trying to implement mac2ip.

**Comment by dMAC95** [comment]
Closed due to non issue
