### ISSUE TITLE
Error when executing

### ISSUE THREAD

**Issue by NelsonLive** [TFyre/bambu-farm#66]
![image](https://github.com/TFyre/bambu-farm/assets/65717208/ca17d020-d0bb-47a3-b7c4-083a2cb215c9)
![image](https://github.com/TFyre/bambu-farm/assets/65717208/dc16368f-6d28-4ad1-bd42-5d6f509494c4)

I am getting this error when executing the java file. I have installed java version 21 correctly and created th .env file.

![image](https://github.com/TFyre/bambu-farm/assets/65717208/ec5115fa-a149-468c-86b8-b7d48291418d)

**Comment by NelsonLive** [comment]
It's fixed, it was a error in the text of the .env file :(

**Comment by TFyre** [comment]
Awesome!! if nothing else, please close the ticket 😄
