### ISSUE TITLE
"Set target temperature" easy access buttons

### ISSUE THREAD

**Issue by wieckowy** [TFyre/bambu-farm#7]
Hi,
I'm testet "Set target" on A1 and P1S for hotend and headbed - unfortunately this option does not work for A1 and P1S.

I also tested sending custom gcode in A1 - this option works properly.

PS - unfortunately this option does not work for A1 and P1S.

I also tested sending custom gcode in A1 - this option works properly.

A good idea is to add small buttons that allow you to quickly warm up the printer to one of the predefined values (this is more convenient than expanding the menu with the right mouse button):

![2024-01-25_183710](https://github.com/TFyre/bambu-farm/assets/1842207/dc59bd2e-a9a0-46eb-8bf7-9fd49beb82fd)

 It would be nice if the user could define these values ​​himself in the settings.

**Comment by wieckowy** [comment]
Update
![2024-01-25_191947](https://github.com/TFyre/bambu-farm/assets/1842207/4fbcc984-54cc-47f7-93d6-0da72c984eb7)

**Comment by TFyre** [comment]
Found the bug, will be solved in the next release...

Leaving the issue open for UI related items

**Comment by TFyre** [comment]
I went a bit in a different direction with this one. For more details check #17 

Since mouse clicks are now normal left clicks, is this ok? Can we close the ticket or do we still need the quick buttons?

**Comment by TFyre** [comment]
Please re-open the ticket if required
