### ISSUE TITLE
Simplify installation using Docker / Docker-Compose

### ISSUE THREAD

**Issue by RyanEwen** [TFyre/bambu-farm#70]
Hi there, 

This project looks amazing, however having a bunch of prerequisites like Java gets in the way for me.

I would like to request the addition of a configured `docker-compose.yml` that would allow someone to get the entire thing running in just a couple of commands. 

Has anyone already done this?

I'm surprised the live-view portion uses docker, but not the rest. 

Cheers

**Comment by RyanEwen** [comment]
Aha, I was able to get this going by cherry-picking parts of the liveview docker example (just the bambuweb service).

**Comment by blasirio** [comment]
Do you think it will run in Synology Docker?

**Comment by TFyre** [comment]
@blasirio Should work if theres enough resources :)

**Comment by Aghost917** [comment]
How would I install this on Docker?

**Comment by TFyre** [comment]
> How would I install this on Docker?

Check out https://github.com/TFyre/bambu-farm/tree/main/docker/bambu-liveview

**Comment by TFyre** [comment]
Closing issue due to non activity
