### ISSUE TITLE
Connect to multiple printers behind the same IP

### ISSUE THREAD

**Issue by victornpb** [TFyre/bambu-farm#72]
I need to connect to 2 printers that are port forwarded behind the same IP, because of that I need to change the default ports.

Is there any way to specify the ports?

**Comment by TFyre** [comment]
Yes! Check this section all config section and look at all the `.port` entries

https://github.com/TFyre/bambu-farm?tab=readme-ov-file#printer-section

**Comment by TFyre** [comment]
Did it work?

**Comment by TFyre** [comment]
Closing issue due to non activity
