### ISSUE TITLE
Everything works but the camera

### ISSUE THREAD

**Issue by TheCableGuy99** [TFyre/bambu-farm#74]
Hi,

I've been at this all night and have tried everything I can think of. It's all working apart from the camera which depending on what options I change either gives me a blank white page or comes up saying "refused to connect".

I'm using the docker version and I have attached my config files (with sensitive data redacted), can you see anything i''m getting wrong please?

To confirm some details:

The printer is called: Bambu 1
The IP of the printer is: 192.168.10.231 (static IP)
The IP of the Raspberry PI 4B is: 192.168.1.227 (static IP)

[compose.yml.txt](https://github.com/TFyre/bambu-farm/files/15137061/compose.yml.txt)
[mediamtx.yml.txt](https://github.com/TFyre/bambu-farm/files/15137062/mediamtx.yml.txt)
[reverse-proxy.conf.txt](https://github.com/TFyre/bambu-farm/files/15137063/reverse-proxy.conf.txt)
[bambu-web-env.txt](https://github.com/TFyre/bambu-farm/files/15137064/bambu-web-env.txt)
[common-liveview.yml.txt](https://github.com/TFyre/bambu-farm/files/15137065/common-liveview.yml.txt)

The logs for the containers are also attached which probably give the issue away but I'm unsure of the issue myself, I'm sure it's just a config error I'm missing Any help would be really appreciated.

[bambu1-mediamtx-1_log.txt](https://github.com/TFyre/bambu-farm/files/15137067/bambu1-mediamtx-1_log.txt)
[bambu1-nginx-1_log.txt](https://github.com/TFyre/bambu-farm/files/15137068/bambu1-nginx-1_log.txt)
[bambu1-printer1-1_log.txt](https://github.com/TFyre/bambu-farm/files/15137069/bambu1-printer1-1_log.txt)

Thank you!

**Comment by TFyre** [comment]
from `mediamtx` container:
```
ERR: json: cannot unmarshal string into Go struct field alias.webrtcAdditionalHosts of type []string
```

from the `printer1` container:
```
[tcp @ 0x55901c3e10] Failed to resolve hostname mediamtx: Name or service not known
```

So issue is that `printer1` video stream cannot find the `mediamtx` container because of config issue.


**Here is the problem:**

mediamtx.yml
```yaml
webrtcAdditionalHosts: 192.168.1.227
```
This should be 
```yaml
webrtcAdditionalHosts: [192.168.1.227]
```

**Comment by TFyre** [comment]
1. Related to the screenshot / connection refused: Its not clear where you want to connect... is this browser or something else?
2. Use common-liveview without any modifications
3. Printer_id should match the printer id from the .env check https://github.com/TFyre/bambu-farm/tree/main/docker/bambu-liveview#adding-your-printers

**Comment by TFyre** [comment]
You have conflicting configuration options

1. Please change `bambu-web-env.txt` to this:
```properties
bambu.dark-mode=true

bambu.use-bouncy-castle=true
bambu.live-view-url=/_camerastream/

bambu.printers.myprinter1.name=Bambu 1
bambu.printers.myprinter1.device-id=00********38
bambu.printers.myprinter1.access-code=*******
bambu.printers.myprinter1.ip=192.168.10.231
bambu.printers.myprinter1.model=x1c
bambu.printers.myprinter1.stream.live-view=true

bambu.users.myusername.password=*********************************
bambu.users.myusername.role=admin

quarkus.http.limits.max-body-size=150M
```

2. Since max-body-size above is 150M, also update `reverse-proxy.conf`:
```
client_max_body_size 150M;
```

3. use original `common-liveview.yml`

4. Start everything again: `docker compose up`

5. Check logs for `mediamtx` container. It should startup without issues. Confirm that it doesnt show this error:
```
ERR: json: cannot unmarshal string into Go struct field alias.webrtcAdditionalHosts of type []string
```
If it still has errors, upload the log file

6. Check logs for `printer1` container. It should startup without issues. Confirm that it doesnt show this error:
```
[tcp @ 0x55901c3e10] Failed to resolve hostname mediamtx: Name or service not known
```

7. Once this is all ready, you should be able to view the printer:
via mediamtx directly: http://192.168.1.227:8889/myprinter1
and via nginx (which is what the frontend would do): http://192.168.1.227:8080/_camerastream/myprinter1
it these dont work, let me know what breaks

8. Test via the normal frontend http://192.168.1.227:8080/

**Comment by TFyre** [comment]
3. Leave everything with fixme's as is... its a template and gets replaced with the compose.yml

------

A. http://192.168.1.227:8889/myprinter1
B. http://192.168.1.227:8080/_camerastream/myprinter1

If A works and B doesnt it means something in nginx is wrong... please make sure you are using the default reverse-proxy.conf with only 1 modification for the body length

All other config is correct at this time 😄 

As soon as the nginx stuff is sorted frontend will work too

**Comment by TFyre** [comment]
> I also note that there are no published ports for the printer container... not sure if this should be like this or not?

Its perfect. The printer container doesnt serve anything. It reads video from the bambu printer and streams it into mediamtx container.

> I asked earlier if this could be a problem with the printer being on a different vLAN? I still suspect this might be a problem?

Its not an issue. Bambu farm can connect to the printer without any issue and you can stream the video from mediamtx with a direct connection. The only thing thats broken is nginx reverse proxy.

Try to run curl and paste the output:
```bash
curl -v http://192.168.1.227:8080/_camerastream/myprinter1
```

**Comment by TFyre** [comment]
Looks like the rewrite in `reverse-proxy.conf` is causing some issues, please replace it with:
```
        rewrite ^/_camerastream/([^.]*[^/])$ /$1/ break;
```


If this works, I will update the template, otherwise please let me know how we can make contact directly so I can debug remotely. Discord? Telegram? Something else?

**Comment by TFyre** [comment]
Haven forgotten about this, currently traveling. Please try to do `docker compose down` to ensure all containers gets deleted and then `docker compose up`.

When Im back from holiday I will reach out via discord so we can setup a direct session 😄
