### ISSUE TITLE
Cameras do not re-connect

### ISSUE THREAD

**Issue by TheCableGuy99** [TFyre/bambu-farm#86]
Hey,

I have X1C printers and when the printer is turned back on the camera stream doesn't seem to re-connect. 

In order for the stream to start working again I must restart the printer container.

I wonder if ffmpeg needs a timeout setting for when the printer is turned off and the stream stops.

Thanks for your consideration.

**Comment by TFyre** [comment]
Adding 30s timeout to ffmpeg in microseconds

```
-timeout 30000000
```
