### ISSUE TITLE
More than 4 printers

### ISSUE THREAD

**Issue by bonninjd** [TFyre/bambu-farm#92]
Can it handle more than 4 printers?  We have a print farm of 10 P1S.  I added all of them, but only the first 4 show.

**Comment by TFyre** [comment]
Yes, for sure!

This is a video received from a customer, I think they have around 50 printers
https://www.youtube.com/watch?v=XEWxZn1SZSQ

**Comment by bonninjd** [comment]
Found the issue.  It was my own mistake.  Thank you much!
